#release configuration
#Fri May 29 12:08:14 WAT 2026
completedPhase=check-poms
exec.activateProfiles=gpg
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.scm.com.zimesfield\:library-starter.empty=true
project.scm.com.zimesfield\:modulith-starter.connection=scm\:git\:https\://github.com/zimesfield/zimesfield-platform.git
project.scm.com.zimesfield\:modulith-starter.developerConnection=scm\:git\:ssh\://git@github.com\:zimesfield/zimesfield-platform.git
project.scm.com.zimesfield\:modulith-starter.tag=HEAD
project.scm.com.zimesfield\:modulith-starter.url=https\://github.com/zimesfield/zimesfield-platform
project.scm.com.zimesfield\:openapi-starter.empty=true
project.scm.com.zimesfield\:platform-bom.empty=true
project.scm.com.zimesfield\:platform-parent.empty=true
project.scm.com.zimesfield\:platform-release.empty=true
project.scm.com.zimesfield\:service-starter.empty=true
project.scm.com.zimesfield\:zimesfield-platform.connection=scm\:git\:https\://github.com/zimesfield/zimesfield-platform.git
project.scm.com.zimesfield\:zimesfield-platform.developerConnection=scm\:git\:ssh\://git@github.com\:zimesfield/zimesfield-platform.git
project.scm.com.zimesfield\:zimesfield-platform.tag=HEAD
project.scm.com.zimesfield\:zimesfield-platform.url=https\://github.com/zimesfield/zimesfield-platform
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:ssh\://git@github.com\:zimesfield/zimesfield-platform.git
