#name: Commons Deploy
name: test

on:
  push:
    branches-ignore:
      - 'main'
      - 'release'

jobs:
  infra:
    uses: zimesfield/devops/.github/workflows/github-ci-maven-lib.yaml@main
    with:
      environment: ${{ github.event.inputs.environment }}
