name: Snapshot Build

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/**
      - bugfix/**

  push:
    branches:
      - main
      - develop
      - feature/**
      - bugfix/**

concurrency:
  group: snapshot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: "-Xmx2g"

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Set snapshot revision
        run: |
          SAFE_BRANCH=$(echo "${GITHUB_REF_NAME}" \
            | tr '/' '-' \
            | tr '[:upper:]' '[:lower:]')

          echo "REVISION=${SAFE_BRANCH}-SNAPSHOT" >> $GITHUB_ENV

      - name: Build
        run: |
          ./mvnw -B clean verify \
            -Drevision=${REVISION} \
            -Dgpg.skip=true \
            --no-transfer-progress