name: Build Snapshot Artifacts

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - develop
      - main

permissions:
  contents: read

concurrency:
  group: maven-snapshot-build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build Snapshot
        run: |
          ./mvnw clean install \
            -B \
            -DskipTests \
            --no-transfer-progress