name: Release

on:
  workflow_dispatch:

jobs:

  publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Import GPG
        run: |
          echo "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}" | base64 -d | gpg --batch --import

      - name: Configure Maven
        run: |
          mkdir -p ~/.m2

          cat > ~/.m2/settings.xml << EOF
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${{ secrets.CENTRAL_TOKEN_USERNAME }}</username>
                <password>${{ secrets.CENTRAL_TOKEN_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Publish
        run: |
          ./mvnw -B clean deploy \
            -pl platform-bom \
            -am \
            -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }}